Add failing test for VM
The VM is what is going to do the fetch, decode, and execute cycle on
the instructions.

This adds the initial outline which does the fetch.

```sh
--- FAIL: TestIntegerArithmetic (0.00s)
    --- FAIL: TestIntegerArithmetic/1 (0.00s)
        vm_test.go:54: object is not Integer. got=<nil> (<nil>)
    --- FAIL: TestIntegerArithmetic/2 (0.00s)
        vm_test.go:54: object is not Integer. got=<nil> (<nil>)
```