Add support for parsing Expression statements
This got a bit hairy. I tried doing a similar approach to Go with a
function being returned, but got errors about lifetimes which I couldn't
figure out.

  error[E0308]: mismatched types
     --> src/parser.rs:132:37
      |
  132 |             Token::Ident(_) => Some(Parser::parse_identifier),
      |                                     ^^^^^^^^^^^^^^^^^^^^^^^^ expected concrete lifetime, found bound lifetime parameter
      |
      = note: expected fn pointer `for<'r, 's> fn(&'r mut parser::Parser<'s>) -> std::result::Result<_, _>`
                    found fn item `for<'r> fn(&'r mut parser::Parser<'_>) -> std::result::Result<_, _> {parser::Parser::<'_>::parse_identifier}`

So instead I've got this version working. We'll see if I need to revist
that decision.